config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  root 'home#index'
  get '/answer/:id', to: 'home#show', as: 'answer'
  post '/answer', to: 'home#check_answer'
  patch '/answer/:id', to: 'home#check_answer'
  resources :questions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/question.rb
class Question < ApplicationRecord
  validates :question, presence: true, length: { minimum: 3 }
  validates :answer, presence: true

    def is_correct?
      h = {"millions" => "millions","hundreds" => "hundred" }
      # convert all number both integer and float in answer to string
      a = answer.gsub(/\d+(\.[\d]+){0,1}/) { |num| (num.to_i == num.to_f)? num.to_i.humanize : num.to_f.humanize }
      s = submitted_answer.gsub(/\d+(\.[\d]+){0,1}/) { |num| (num.to_i == num.to_f)? num.to_i.humanize : num.to_f.humanize }
      # remove unnecesary character and whitespaces including - 
      a.gsub(/[(),.-]/, ' ').downcase.strip.squeeze(' ').gsub(/\w+/) { |m| h.fetch(m,m)} == s.gsub(/[(),.-]/, ' ').downcase.strip.squeeze(' ').gsub(/\w+/) { |m| h.fetch(m,m)} 
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @random_id = Question.pluck(:id).sample
    @questions = Question.select(:id, :question).order("updated_at desc").page(params[:page]).per(5)
    respond_to do |format|
      format.js
      format.html
    end
  end

  def show
    @question = Question.select(:id, :question).find(params[:id])
    @question.submitted_answer =''
    @status = -1  # status unset 
    render 'show'
  end

  def check_answer
    @question = Question.find(params[:id])
    @question.update_attributes(question_param)
    if @question.is_correct?
      flash.now[:success] = "Congratulation. Your answer is correct"
      @status = 1
      render 'show'
    else
      flash.now[:alert] = "Your answer is not correct. Try again !"
      render 'show'
      @status = 0
    end 
  end

  def question_param
    params.require(:question).permit(:submitted_answer)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  

  def index
    @questions = Question.order("updated_at desc").page(params[:page]).per(5)
    respond_to do |format|
      format.html
      format.js { render :layout => false }
    end
  end

  def show
  end

  def new
    @question = Question.new
  end

  def edit
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to action: "index"
      flash.now[:success] = "Question was successfully created"
    else
      render :new
    end
  end

  def update
    if @question.update(question_params)
      redirect_to action: "index"
      flash.now[:success] = "Question was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to questions_url, notice: 'Question was successfully destroyed.'
  end

  private
    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:question, :answer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/home/index.html.erb
<div class="center jumbotron">
    <h3><strong>Welcome to Questionaire</strong></h3>
    <h4>
      You are challenged to answer question. </br>
      <% if !@random_id.nil? -%>
      Picked randomly <%= link_to fa_icon(:try, text: "Try"), answer_path(@random_id), class: "btn btn-success" %> </br>
      or Pick one below
      <% else -%>
      But, looks like there are no question. <%= link_to "Create question", new_question_path, class: "btn btn-success" %> </br>
      <% end -%>
    </h4>
</div>

<table class="table table-hover col-md-8">
  <thead>
    <tr>
      <th class="col-md-6"><h4>Question</h4></th>
      <th class="col-md-2"></th>
    </tr>
  </thead>
 
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td class="col-md-6"><%= question.question.html_safe %></td>
        <td class="col-md-2"><%= link_to fa_icon(:try, text: "Try"), answer_path(question.id), class: "btn btn-success" %>
        </td>
      </tr>
    <% end %>
  </tbody>
  
</table>

<center>
  <%= paginate @questions, window: 3, theme: 'twitter-bootstrap-4' %>
</center>

app/views/home/show.html.erb
<p id="notice"><%= notice %></p>

<div class="well">
  <p>
    <h4>Question :</h4>
  </p>
  <p>
    <%= @question.question.html_safe %>
  </p>
</div>
<%= form_for @question, :url => answer_path do |f| %>
  <div class="field">
    <h4><%= f.label "Your Answer :" %></h4>
    <%= f.text_field :submitted_answer, class: "form-control" %>
  </div>
  <br/>
  <div class="actions">
    <%= f.submit "Answer", class: "btn btn-success" %>
  </div>
<% end %>

 <center>
<%= link_to fa_icon("chevron-left", text: " Back"), root_path, class: "btn btn-primary"%>
 </center>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
    <%= link_to fa_icon("trophy", text: " QUIZ MASTER"), root_path, id:"logo"  %>
    <button type="button" class="btn navbar-toggle" data-toggle="collapse" 
    data-target=".navbar-collapse" >
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
    </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right" >
        <li><%= link_to "Manage Questions", questions_path %></li>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />
    <title>Questionaire</title>
  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= favicon_link_tag 'favicon.png' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no, target-densityDpi=device-dpi" />
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for(question) do |f| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <h4><%= f.label "Question :" %></h4>
    <%= f.cktext_area :question %>
  </div>

  <div class="field">
    <h4><%= f.label "Answer :" %></h4>
    <%= f.text_field :answer, class: "form-control" %>
  </div>
  <br/>
 <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>
 <center>
<%= link_to fa_icon("chevron-left", text: " Back"), questions_path, class: "btn btn-primary"%>
 </center>

app/views/questions/index.html.erb
<h1>List of Questions</h1>

<%= link_to fa_icon(:plus, text: " New Question"), new_question_path, class: "btn btn-primary"%>

<table class="table table-hover">
  <thead>
    <tr>
      <th><h4>Question</h4></th>
      <th></th>
    </tr>
  </thead>
 
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td class="col-md-6"><%= question.question.html_safe %></td>
        <td class="col-md-4"> 
        <%= link_to fa_icon(:eye, text: "Show"), question, class: "btn btn-success" %>
        <%= link_to fa_icon(:pencil, text: "Edit"), edit_question_path(question), class: "btn btn-warning" %>
        <%= link_to fa_icon(:trash, text: "Delete"), question, method: :delete,
        data: { confirm: 'Are you sure to delete this one?' }, class: "btn btn-danger" %> 
        </td>
      </tr>
    <% end %>
  </tbody>
  
</table>
<center>
  <%= paginate @questions, window: 3, theme: 'twitter-bootstrap-4' %>
</center>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>
 <center>
<%= link_to fa_icon("chevron-left", text: " Back"), questions_path, class: "btn btn-primary"%>
 </center>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h4>Question :</h4>
</p>
<p >
  <%= @question.question.html_safe %>
</p>

<p>
  <h4>Answer :</h4>
</p>
<p class="well" >
  <%= @question.answer %>
</p>
 <center>
<%= link_to fa_icon("chevron-left", text: " Back"), questions_path, class: "btn btn-primary"%>
 </center>